apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-db
  name: service-db-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: service-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-db
    spec:
      containers:
        - image: mista123/servicedb:latest
          name: service-db
          env:
            - name: DB_URL
              value: "83.212.127.63"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: TOKEN_URL
              value: "://51.104.153.48/:8081/v1/token"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: postgres_pass
            - name: DB_NAME
              value: "mistrdb2"
          ports:
            - containerPort: 8094
              name: server
              protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: service-db
spec:
  type: LoadBalancer
  ports:
    - port: 8094
      protocol: TCP
      targetPort: server
  selector:
    app: service-db