apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-db
  name: service-db-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: service-db
  template:
    metadata:
      labels:
        app: service-db
    spec:
      containers:
        - image: mista123/servicedb:latest
          name: service-db
          env:
            - name: DB_URL
              value: "83.212.127.63"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets2
                  key: postgres_pass
            - name: DB_NAME
              value: "mistrdb2"
            - name: TOKEN_URL
              value: "http://51.132.211.245:8081/v1/token"
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/health/live_check
              port: server
            initialDelaySeconds: 5
            periodSeconds: 10

---


apiVersion: v1
kind: Service
metadata:
  name: service-db
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: service-db
